### ISSUE TITLE
Add support for Arabic / English language

### ISSUE THREAD

**Issue by yazinsai** [yazinsai/redshirt#9]
We can [autodetect the language](https://stackoverflow.com/a/35493069/2022751), so no additional screen is necessary.

Would need to:

- Add i18n support
- Extract all text to separate files that include both Arabic and English text
- Style screens differently based on language selected (RTL vs LTR)
- Update API to return both languages

**Comment by yazinsai** [comment]
Hi Oscar, some initial comments (I'm still testing the whole PR):

- In the Arabic onboarding slides, you have to swipe right to move to the next slide (not left as in `en`)
- Arabic onboarding slides: dot highlighting should start from the right, not left (see below):

![image](https://user-images.githubusercontent.com/1846034/51523643-34d93800-1e3d-11e9-9e3a-ba1ef2baa909.png)

- In Arabic, the screen transition animation should proceed from Left to Right
- In Arabic, we should use the [Geeza Pro font -- Bold/Regular](http://fontsgeek.com/fonts/Geeza-Pro-Bold) with a font size that is slightly smaller than the English text, depending on the context

When implementing these features, I want you to be mindful of the code quality. We don't want to add complexity without consideration for how things work overall. 

I need the code to be maintainable.

**Comment by redshirtHQ** [comment]
@lagartoverde The selectLaundry screen needs to be RTL in Arabic:

![image](https://user-images.githubusercontent.com/46918887/51931908-08aa5200-240f-11e9-95c0-4adc4346894a.png)

The text/image should be right-aligned, not left-aligned as in the image above.

**Comment by redshirtHQ** [comment]
Also, notice the "< Back" text in the header in English:

![image](https://user-images.githubusercontent.com/46918887/51932024-5b840980-240f-11e9-81cc-9d5387da2b1d.png)

**Comment by redshirtHQ** [comment]
Also, the price screen should be RTL:

![image](https://user-images.githubusercontent.com/46918887/51932132-8ec69880-240f-11e9-8132-7333714fec25.png)

**Comment by redshirtHQ** [comment]
None of the labels on the orderDetails screen are translated in Arabic (even though I added the strings):

![image](https://user-images.githubusercontent.com/46918887/51932377-20cea100-2410-11e9-9afd-25b92e5a902f.png)

**Comment by redshirtHQ** [comment]
And why is the Picker text not right-aligned?

![image](https://user-images.githubusercontent.com/46918887/51932459-478cd780-2410-11e9-80a6-2e4f54fbf2b5.png)

It seems like this is really hacky, especially the code littered all over the `orderDetails` screens that says:

![image](https://user-images.githubusercontent.com/46918887/51932515-5ffcf200-2410-11e9-9f81-eb5aafa58840.png)

Can't you just apply the writingDirection to the whole screen, and have it inherited by all the child elements?

**Comment by redshirtHQ** [comment]
Oh, and the "Back" button in Arabic needs to be on the right side:

![image](https://user-images.githubusercontent.com/46918887/51932668-a2beca00-2410-11e9-8bd4-e62aa0fe2f8c.png)
